### ISSUE TITLE
[1.15.2 fabric] random crashes when using optifine

### ISSUE THREAD

**Issue by cs127** [comp500/ScreenshotToClipboard#6]
the crashes happen randomly, and also when I take a screenshot.
optifine version: 1.15.2 G1 pre13
optifabric version: 1.0.0 beta 8
screenshot to clipboard version: 1.0.4

**Comment by comp500** [comment]
Sorry about not responding to this, it didn't show up in my GitHub inbox! I'll talk to modmuss about whether I can get the mixins working with Optifine classes.

Unfortunately I feel like this might be somewhat difficult though, and I don't really want to support Optifine because it's closed-source so issues are hard to debug.
